apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-example-app
spec:
  replicas: 2 # You can adjust the number of replicas
  selector:
    matchLabels:
      app: argocd-example-app
  template:
    metadata:
      labels:
        app: argocd-example-app
    spec:
      containers:
      - name: argocd-example-app
        image: hashicorp/http-echo:1.0
        args: ["-listen=:3000", "-text=1.0.0"]
        ports:
        - containerPort: 3000

